'use client';
import { createContext, useContext, useState, useCallback } from 'react';

const translations = {
  ar: {
    dir: 'rtl',
    // Navbar
    brand: 'عبايتي المتميزة',
    home: 'الرئيسية',
    allAbayas: 'كل العبايات',
    dashboard: 'لوحة التحكم',
    cart: 'السلة',
    login: 'دخول',
    register: 'تسجيل',
    logout: 'خروج',
    // Shop
    all: 'الكل',
    heroTitle: 'عبايتي المتميزة',
    heroSub: 'تشكيلة راقية من العبايات الملكية بأفخم الأقمشة',
    loading: 'جاري التحميل...',
    noProducts: 'لا توجد منتجات متاحة حالياً',
    fabric: 'القماش',
    size: 'المقاس',
    color: 'اللون',
    style: 'الموديل',
    notSpecified: 'غير محدد',
    addToCart: 'أضف للسلة',
    limited: 'محدود',
    items: 'منتج',
    // Product
    outOfStock: 'نفذ المخزون',
    inStock: 'متوفر',
    backToShop: 'العودة للمتجر',
    // Cart
    shoppingCart: 'سلة التسوق',
    emptyCart: 'سلتك فارغة',
    emptyCartSub: 'تصفحي أحدث العبايات وأضيفيها هنا',
    quantity: 'الكمية',
    subtotal: 'المجموع',
    vat: 'ضريبة القيمة المضافة (15%)',
    total: 'الإجمالي',
    checkout: 'إتمام الشراء',
    sar: 'ر.س',
    orderSuccess: 'تم تأكيد طلبك بنجاح!',
    errorOrder: 'حدث خطأ في إتمام الطلب',
    // Auth
    loginTitle: 'تسجيل الدخول',
    loginSub: 'أهلاً بعودتك',
    email: 'البريد الإلكتروني',
    password: 'كلمة المرور',
    loggingIn: 'جاري الدخول...',
    noAccount: 'ليس لديك حساب؟',
    registerNow: 'سجل الآن',
    registerTitle: 'إنشاء حساب',
    registerSub: 'انضمي إلينا اليوم',
    fullName: 'الاسم الكامل',
    creatingAccount: 'جاري الإنشاء...',
    createAccount: 'إنشاء حساب',
    haveAccount: 'لديك حساب؟',
    loginNow: 'سجل دخولك',
    ruleLength: '8 أحرف على الأقل',
    ruleUpper: 'حرف كبير (A-Z)',
    ruleLower: 'حرف صغير (a-z)',
    ruleNumber: 'رقم (0-9)',
    // Errors
    EMAIL_NOT_FOUND: 'البريد الإلكتروني غير مسجل',
    WRONG_PASSWORD: 'كلمة المرور غير صحيحة',
    MISSING_FIELDS: 'يرجى تعبئة جميع الحقول',
    loginFailed: 'فشل تسجيل الدخول',
    oauth: 'فشل تسجيل الدخول عبر الحساب الخارجي',
    orContinueWith: 'أو تابع عبر',
    errorRegister: 'حدث خطأ أثناء التسجيل',
    // Dashboard
    dashboardTitle: 'لوحة التحكم',
    totalRevenue: 'إجمالي الإيرادات',
    totalVat: 'ضريبة القيمة المضافة',
    totalOrders: 'إجمالي الطلبات',
    totalProducts: 'المنتجات',
    totalUsers: 'المستخدمون',
    products: 'المنتجات',
    users: 'المستخدمون',
    orders: 'الطلبات',
    addProduct: 'إضافة منتج',
    editProduct: 'تعديل المنتج',
    deleteProduct: 'حذف المنتج',
    noProducts2: 'لا توجد منتجات',
    noUsers: 'لا يوجد مستخدمون',
    noOrders: 'لا توجد طلبات',
    name: 'الاسم',
    role: 'الصلاحية',
    admin: 'مدير',
    customer: 'عميل',
    registeredAt: 'تاريخ التسجيل',
    price: 'السعر',
    qty: 'الكمية',
    image: 'الصورة',
    titleAr: 'الاسم (عربي)',
    titleEn: 'الاسم (إنجليزي)',
    description: 'الوصف',
    descEn: 'الوصف (إنجليزي)',
    fabricAr: 'القماش (عربي)',
    fabricEn: 'القماش (إنجليزي)',
    colorEn: 'اللون (إنجليزي)',
    save: 'حفظ',
    cancel: 'إلغاء',
    del: 'حذف',
    edit: 'تعديل',
    confirmDelete: 'تأكيد الحذف',
    deleteConfirmMsg: 'هل أنت متأكد من حذف',
    invoiceNo: 'رقم الطلب',
    date: 'التاريخ',
    payment: 'طريقة الدفع',
    amount: 'المبلغ',
    welcome: 'مرحباً',
    errorFetch: 'خطأ في تحميل البيانات — تأكد من تسجيل الدخول كمدير',
    selectStyle: 'اختر الموديل',
    // Forgot / Reset password
    enterEmailFirst: 'أدخل بريدك الإلكتروني أولاً لاستعادة كلمة المرور',
    forgotPassword: 'نسيت كلمة المرور؟',
    forgotPasswordTitle: 'استعادة كلمة المرور',
    forgotPasswordSub: 'أدخلي بريدك الإلكتروني وسنرسل لك رابط الاستعادة',
    sendResetLink: 'إرسال رابط الاستعادة',
    sending: 'جاري الإرسال...',
    backToLogin: 'العودة لتسجيل الدخول',
    RESET_EMAIL_SENT: 'تم إرسال رابط الاستعادة على بريدك الإلكتروني ✉️',
    INVALID_OR_EXPIRED_TOKEN: 'الرابط غير صالح أو انتهت صلاحيته',
    resetPasswordTitle: 'كلمة مرور جديدة',
    resetPasswordSub: 'أدخلي كلمة مرورك الجديدة',
    newPassword: 'كلمة المرور الجديدة',
    confirmPassword: 'تأكيد كلمة المرور',
    resetPasswordBtn: 'تعيين كلمة المرور',
    resetting: 'جاري التعيين...',
    PASSWORD_RESET_SUCCESS: 'تم تغيير كلمة المرور بنجاح! يمكنك تسجيل الدخول الآن.',
    passwordMismatch: 'كلمتا المرور غير متطابقتين',
    // About & Contact
    aboutUs: 'من نحن',
    contactUs: 'تواصل معنا',
    aboutHero: 'قصتنا مع الأناقة',
    aboutHeroSub: 'نؤمن أن كل امرأة تستحق عباءة تعكس شخصيتها وتُضفي عليها لمسة من الفخامة',
    ourStory: 'قصتنا',
    ourStoryText: 'انطلقت عبايتي المتميزة من حلم بسيط — تقديم عباءات ذات جودة فاخرة تجمع بين الأصالة والعصرية. بدأنا رحلتنا بشغف حقيقي لتمكين المرأة العربية من التعبير عن أناقتها بثقة واحترام.',
    ourMission: 'مهمتنا',
    ourMissionText: 'نسعى لأن نكون الوجهة الأولى للمرأة التي تبحث عن العباءة المثالية — من الأقمشة الفاخرة إلى التصاميم العصرية التي تناسب كل مناسبة.',
    ourValues: 'قيمنا',
    quality: 'الجودة',
    qualityText: 'نختار أجود الأقمشة من مصادر موثوقة لضمان راحتك وأناقتك.',
    elegance: 'الأناقة',
    eleganceText: 'كل تصميم يحمل بصمة فريدة تجمع الموروث الثقافي بالذوق الرفيع.',
    trust: 'الثقة',
    trustText: 'نبني علاقة طويلة الأمد مع كل عميلة مبنية على الصدق والاحترام.',
    contactHero: 'نسعد بتواصلك',
    contactHeroSub: 'فريقنا جاهز للإجابة على جميع استفساراتك',
    yourName: 'اسمك',
    yourEmail: 'بريدك الإلكتروني',
    yourMessage: 'رسالتك',
    sendMessage: 'إرسال الرسالة',
    messageSent: 'تم إرسال رسالتك بنجاح! سنتواصل معك قريباً.',
    phone: 'الهاتف',
    address: 'العنوان',
    riyadh: 'الرياض، المملكة العربية السعودية',
    workingHours: 'ساعات العمل',
    workingHoursVal: 'الأحد - الخميس: 9ص - 6م',
    // Profile
    myProfile: 'ملفي الشخصي',
    profileTitle: 'الملف الشخصي',
    profileSub: 'إدارة بياناتك الشخصية وكلمة المرور',
    personalInfo: 'المعلومات الشخصية',
    changePhoto: 'تغيير الصورة',
    choosePhoto: 'اختر صورة',
    uploadPhoto: 'رفع الصورة',
    security: 'الأمان',
    currentPassword: 'كلمة المرور الحالية',
    saveChanges: 'حفظ التغييرات',
    saving: 'جاري الحفظ...',
    PROFILE_UPDATED: 'تم تحديث ملفك الشخصي بنجاح ✅',
    EMAIL_TAKEN: 'هذا البريد الإلكتروني مستخدم بالفعل',
    WRONG_CURRENT_PASSWORD: 'كلمة المرور الحالية غير صحيحة',
    CURRENT_PASSWORD_REQUIRED: 'أدخل كلمة المرور الحالية لتغييرها',
    leaveBlankPassword: 'اتركها فارغة إذا لم تريد تغيير كلمة المرور',
    memberSince: 'عضو منذ',
    // Footer
    privacyPolicy: 'سياسة الخصوصية',
    termsConditions: 'الشروط والأحكام',
    allRightsReserved: 'جميع الحقوق محفوظة',
  },
  en: {
    dir: 'ltr',
    brand: 'My Premium Abaya',
    home: 'Home',
    allAbayas: 'All Abayas',
    dashboard: 'Dashboard',
    cart: 'Cart',
    login: 'Login',
    register: 'Register',
    logout: 'Logout',
    all: 'All',
    heroTitle: 'My Premium Abaya',
    heroSub: 'An elegant collection of royal abayas in the finest fabrics',
    loading: 'Loading...',
    noProducts: 'No products available at the moment',
    fabric: 'Fabric',
    size: 'Size',
    color: 'Color',
    style: 'Style',
    notSpecified: 'Not specified',
    addToCart: 'Add to Cart',
    limited: 'Limited',
    items: 'items',
    outOfStock: 'Out of Stock',
    inStock: 'In Stock',
    backToShop: 'Back to Shop',
    shoppingCart: 'Shopping Cart',
    emptyCart: 'Your cart is empty',
    emptyCartSub: 'Browse our latest collection and add items here',
    quantity: 'Qty',
    subtotal: 'Subtotal',
    vat: 'VAT (15%)',
    total: 'Total',
    checkout: 'Checkout',
    sar: 'SAR',
    orderSuccess: 'Your order has been placed successfully!',
    errorOrder: 'Error placing order',
    loginTitle: 'Welcome Back',
    loginSub: 'Sign in to your account',
    email: 'Email',
    password: 'Password',
    loggingIn: 'Signing in...',
    noAccount: "Don't have an account?",
    registerNow: 'Register',
    registerTitle: 'Create Account',
    registerSub: 'Join us today',
    fullName: 'Full Name',
    creatingAccount: 'Creating...',
    createAccount: 'Create Account',
    haveAccount: 'Already have an account?',
    loginNow: 'Sign in',
    ruleLength: 'At least 8 characters',
    ruleUpper: 'Uppercase (A-Z)',
    ruleLower: 'Lowercase (a-z)',
    ruleNumber: 'Number (0-9)',
    EMAIL_NOT_FOUND: 'Email not registered',
    WRONG_PASSWORD: 'Wrong password',
    MISSING_FIELDS: 'Please fill all fields',
    loginFailed: 'Login failed',
    oauth: 'Sign-in via external account failed',
    orContinueWith: 'Or continue with',
    errorRegister: 'Registration failed',
    dashboardTitle: 'Dashboard',
    totalRevenue: 'Total Revenue',
    totalVat: 'VAT Collected',
    totalOrders: 'Total Orders',
    totalProducts: 'Products',
    totalUsers: 'Users',
    products: 'Products',
    users: 'Users',
    orders: 'Orders',
    addProduct: 'Add Product',
    editProduct: 'Edit Product',
    deleteProduct: 'Delete Product',
    noProducts2: 'No products found',
    noUsers: 'No users found',
    noOrders: 'No orders found',
    name: 'Name',
    role: 'Role',
    admin: 'Admin',
    customer: 'Customer',
    registeredAt: 'Registered',
    price: 'Price',
    qty: 'Qty',
    image: 'Image',
    titleAr: 'Title (Arabic)',
    titleEn: 'Title (English)',
    description: 'Description',
    descEn: 'Description (English)',
    fabricAr: 'Fabric (Arabic)',
    fabricEn: 'Fabric (English)',
    colorEn: 'Color (English)',
    save: 'Save',
    cancel: 'Cancel',
    del: 'Delete',
    edit: 'Edit',
    confirmDelete: 'Confirm Delete',
    deleteConfirmMsg: 'Are you sure you want to delete',
    invoiceNo: 'Order #',
    date: 'Date',
    payment: 'Payment',
    amount: 'Amount',
    welcome: 'Welcome',
    errorFetch: 'Error loading data — make sure you are logged in as admin',
    selectStyle: 'Select Style',
    // Forgot / Reset password
    enterEmailFirst: 'Enter your email first to reset your password',
    forgotPassword: 'Forgot password?',
    forgotPasswordTitle: 'Reset Password',
    forgotPasswordSub: "Enter your email and we'll send you a reset link",
    sendResetLink: 'Send Reset Link',
    sending: 'Sending...',
    backToLogin: 'Back to Login',
    RESET_EMAIL_SENT: 'Reset link sent to your email ✉️',
    INVALID_OR_EXPIRED_TOKEN: 'Link is invalid or has expired',
    resetPasswordTitle: 'New Password',
    resetPasswordSub: 'Enter your new password below',
    newPassword: 'New Password',
    confirmPassword: 'Confirm Password',
    resetPasswordBtn: 'Reset Password',
    resetting: 'Resetting...',
    PASSWORD_RESET_SUCCESS: 'Password changed successfully! You can now sign in.',
    passwordMismatch: 'Passwords do not match',
    // About & Contact
    aboutUs: 'About Us',
    contactUs: 'Contact Us',
    aboutHero: 'Our Story of Elegance',
    aboutHeroSub: 'We believe every woman deserves an abaya that reflects her personality and adds a touch of luxury',
    ourStory: 'Our Story',
    ourStoryText: 'My Premium Abaya was born from a simple dream — to offer luxury-quality abayas that blend heritage with modernity. We began with a genuine passion for empowering Arab women to express their elegance with confidence.',
    ourMission: 'Our Mission',
    ourMissionText: 'We strive to be the first destination for women seeking the perfect abaya — from luxurious fabrics to contemporary designs that suit every occasion.',
    ourValues: 'Our Values',
    quality: 'Quality',
    qualityText: 'We source only the finest fabrics from trusted suppliers to ensure your comfort and elegance.',
    elegance: 'Elegance',
    eleganceText: 'Each design carries a unique touch that blends cultural heritage with refined taste.',
    trust: 'Trust',
    trustText: 'We build long-term relationships with every customer based on honesty and respect.',
    contactHero: 'We\'d Love to Hear From You',
    contactHeroSub: 'Our team is ready to answer all your inquiries',
    yourName: 'Your Name',
    yourEmail: 'Your Email',
    yourMessage: 'Your Message',
    sendMessage: 'Send Message',
    messageSent: 'Your message was sent successfully! We\'ll be in touch soon.',
    phone: 'Phone',
    address: 'Address',
    riyadh: 'Riyadh, Saudi Arabia',
    workingHours: 'Working Hours',
    workingHoursVal: 'Sun - Thu: 9AM - 6PM',
    // Profile
    myProfile: 'My Profile',
    profileTitle: 'My Profile',
    profileSub: 'Manage your personal information and password',
    personalInfo: 'Personal Information',
    changePhoto: 'Change Photo',
    choosePhoto: 'Choose Photo',
    uploadPhoto: 'Upload Photo',
    security: 'Security',
    currentPassword: 'Current Password',
    saveChanges: 'Save Changes',
    saving: 'Saving...',
    PROFILE_UPDATED: 'Profile updated successfully ✅',
    EMAIL_TAKEN: 'This email is already in use',
    WRONG_CURRENT_PASSWORD: 'Current password is incorrect',
    CURRENT_PASSWORD_REQUIRED: 'Enter current password to change it',
    leaveBlankPassword: 'Leave blank to keep your current password',
    memberSince: 'Member since',
    privacyPolicy: 'Privacy Policy',
    termsConditions: 'Terms & Conditions',
    allRightsReserved: 'All rights reserved',
  },
};

const LangContext = createContext(null);

export const useLang = () => useContext(LangContext);

export function LangProvider({ children }) {
  const [lang, setLang] = useState('ar');

  const toggleLang = useCallback(() => {
    setLang((prev) => (prev === 'ar' ? 'en' : 'ar'));
  }, []);

  const t = useCallback((key) => translations[lang]?.[key] ?? key, [lang]);

  const dir = translations[lang].dir;

  return (
    <LangContext.Provider value={{ lang, toggleLang, t, dir }}>
      {children}
    </LangContext.Provider>
  );
}
